version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs-backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 12345678
      DATABASE_NAME: book_reco

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5433"
    environment:
      DATABASE_PORT: 5433
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: book_reco
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
